In [12]:
import numpy as np
def construct_matrix(first_array, second_array):
    return np.reshape(np.hstack((first_array, second_array)), (first_array.size,2), order='F')
print(construct_matrix(np.array([1,2,3]), np.array([4,5,6])))

[[1 4]
 [2 5]
 [3 6]]


In [5]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.vstack((a,b)))

[[1 2 3]
 [4 5 6]]
